/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { ComplaintCategory } from './complaintCategory';
import { User } from './user';
import { ComplaintType } from './complaintType';


export interface Claim { 
    id?: number;
    description?: string;
    complaintCategory?: ComplaintCategory;
    complaintType?: ComplaintType;
    user?: User;
    order?: Order;
}

