export * from './attachmentCategoryRestController.service';
import { AttachmentCategoryRestControllerService } from './attachmentCategoryRestController.service';
export * from './attachmentRestController.service';
import { AttachmentRestControllerService } from './attachmentRestController.service';
export * from './cityRestController.service';
import { CityRestControllerService } from './cityRestController.service';
export * from './complaintCategoryRestController.service';
import { ComplaintCategoryRestControllerService } from './complaintCategoryRestController.service';
export * from './countryRestController.service';
import { CountryRestControllerService } from './countryRestController.service';
export * from './itemCategoryRestController.service';
import { ItemCategoryRestControllerService } from './itemCategoryRestController.service';
export * from './itemRestController.service';
import { ItemRestControllerService } from './itemRestController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './orderLineRestController.service';
import { OrderLineRestControllerService } from './orderLineRestController.service';
export * from './orderStatusRestController.service';
import { OrderStatusRestControllerService } from './orderStatusRestController.service';
export * from './userGenderRestController.service';
import { UserGenderRestControllerService } from './userGenderRestController.service';
export * from './userRestController.service';
import { UserRestControllerService } from './userRestController.service';
export * from './userStatusRestController.service';
import { UserStatusRestControllerService } from './userStatusRestController.service';
export * from './userTypeRestController.service';
import { UserTypeRestControllerService } from './userTypeRestController.service';
export const APIS = [AttachmentCategoryRestControllerService, AttachmentRestControllerService, CityRestControllerService, ComplaintCategoryRestControllerService, CountryRestControllerService, ItemCategoryRestControllerService, ItemRestControllerService, OrderControllerService, OrderLineRestControllerService, OrderStatusRestControllerService, UserGenderRestControllerService, UserRestControllerService, UserStatusRestControllerService, UserTypeRestControllerService];
